### ISSUE TITLE
BUG: si pulsas sobre un botón de favoritos vacío, la aplicacón forza cierre

### ISSUE THREAD

**Issue by bal0n** [bal0n/BMB#78]

**Comment by bal0n** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: es.bmb.bmbelnavegadorseguro, PID: 21060
                  java.lang.IllegalStateException: Could not find method DarBoton(View) in a parent or ancestor Context for android:onClick attribute defined on view class android.support.v7.widget.AppCompatButton with id 'btnFavorito13'
                      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.resolveMethod(AppCompatViewInflater.java:327)
                      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:284)
                      at android.view.View.performClick(View.java:6289)
                      at android.view.View$PerformClick.run(View.java:24800)
                      at android.os.Handler.handleCallback(Handler.java:789)
                      at android.os.Handler.dispatchMessage(Handler.java:98)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6809)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by bal0n** [comment]
Cambio de planes Pablo, deshabilita todos los botones de favorios y los habilitas/deshabilitas cuando sea necesario. Así solucionamos el error sin complicarnos en código.

**Comment by bal0n** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: es.bmb.bmbelnavegadorseguro, PID: 22638
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{es.bmb.bmbelnavegadorseguro/es.bmb.bmbelnavegadorseguro.ActivityFavoritos}: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3046)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6809)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                   Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
                      at java.util.ArrayList.get(ArrayList.java:437)
                      at es.bmb.bmbelnavegadorseguro.ActivityFavoritos.ajusteInformacion(ActivityFavoritos.java:202)
                      at es.bmb.bmbelnavegadorseguro.ActivityFavoritos.guardar(ActivityFavoritos.java:192)
                      at es.bmb.bmbelnavegadorseguro.ActivityFavoritos.Ensamblador(ActivityFavoritos.java:121)
                      at es.bmb.bmbelnavegadorseguro.ActivityFavoritos.extractor(ActivityFavoritos.java:106)
                      at es.bmb.bmbelnavegadorseguro.ActivityFavoritos.inicializador(ActivityFavoritos.java:83)
                      at es.bmb.bmbelnavegadorseguro.ActivityFavoritos.onCreate(ActivityFavoritos.java:72)
                      at android.app.Activity.performCreate(Activity.java:6998)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1230)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2899)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3046) 
                      at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688) 
                      at android.os.Handler.dispatchMessage(Handler.java:105) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6809) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
